version: '3'

services:
    db:
        image: 'postgres:13'
        container_name: 'insta_db'
        ports:
            - 15432:5432
        environment:
            - 'POSTGRES_DB=insta'
            - 'POSTGRES_USER=admin'
            - 'POSTGRES_PASSWORD=123'
        volumes:
            - insta-data:/var/lib/postgresql/data

volumes:
    insta-data:
